apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: shared-db
  namespace: user
  labels:
    app: shared-db
    operator: cloudnativepg
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: shared-db
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
  podTargetLabels:
    - cnpg.io/cluster
    - cnpg.io/instanceRole
    - cnpg.io/instanceName
