apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: apm
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: cart
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: cache-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: cloudnative-pg
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: k6
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: notification
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: order
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: postgres-operator
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: product
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: review
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: rustfs
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: shipping
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: local
  name: user
