apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth.yaml
  - cart.yaml
  - notification.yaml
  - order.yaml
  - product.yaml
  - review.yaml
  - shipping-v2.yaml
  - shipping.yaml
  - user.yaml
