---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: apps-oci
  namespace: flux-system
  labels:
    app.kubernetes.io/component: apps
spec:
  interval: 5m
  url: oci://localhost:5050/flux-apps-sync
  ref:
    tag: latest
  insecure: true
