---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OCI Repositories
  - oci/infrastructure-oci.yaml
  - oci/apps-oci.yaml
  - oci/mop-chart-oci.yaml
  - oci/grafana-operator-oci.yaml
  - oci/victoria-metrics-operator-oci.yaml
  - oci/cronjobs-oci.yaml
  - oci/victoria-metrics-mcp-oci.yaml
  - oci/victoria-logs-mcp-oci.yaml
  - oci/flux-operator-mcp-oci.yaml
  
  # Helm Repositories
  - helm/prometheus-community.yaml
  - helm/metrics-server.yaml
  - helm/jaegertracing.yaml
  - helm/postgres-operator.yaml
  - helm/postgres-operator-ui.yaml
  - helm/cnpg.yaml
  - helm/sloth.yaml
  - helm/vector.yaml
  - helm/opentelemetry.yaml
  - helm/pgcat.yaml
  - helm/pgdog.yaml
  - helm/rustfs.yaml
  - helm/valkey.yaml
  - helm/external-secrets.yaml
  - helm/openbao.yaml
  - helm/jetstack.yaml
  - helm/kong.yaml
  - helm/kyverno.yaml
