---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OCI Repositories
  - oci/infrastructure-oci.yaml
  - oci/apps-oci.yaml
  - oci/mop-chart-oci.yaml
  - oci/grafana-operator-oci.yaml
  - oci/victorialogs-oci.yaml
  
  # Helm Repositories
  - helm/prometheus-community.yaml
  - helm/metrics-server.yaml
  - helm/jaegertracing.yaml
  - helm/postgres-operator.yaml
  - helm/cnpg.yaml
  - helm/sloth.yaml
  - helm/vector.yaml
  - helm/opentelemetry.yaml
  - helm/pgcat.yaml
  - helm/pgdog.yaml