---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OCI Repositories
  - infrastructure-oci.yaml
  - apps-oci.yaml
  - mop-chart-oci.yaml
  
  # Helm Repositories
  - helm/prometheus-community.yaml
  - helm/grafana.yaml
  - helm/metrics-server.yaml
  - helm/jaegertracing.yaml
  - helm/postgres-operator.yaml
  - helm/cnpg.yaml
  - helm/sloth.yaml
  - helm/vector.yaml
  - helm/opentelemetry.yaml
  - helm/pgcat.yaml
  - helm/pgdog.yaml