apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: monitoring
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    name: Prometheus
    type: prometheus
    uid: prometheus
    # VMSingle is fully Prometheus API compatible
    url: http://vmsingle-victoria-metrics.monitoring.svc:8428
  instanceSelector:
    matchLabels:
      dashboards: grafana
