---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shipping
  namespace: shipping
  labels:
    app.kubernetes.io/name: shipping
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: v1
spec:
  interval: 10m
  timeout: 5m
  
  chartRef:
    kind: OCIRepository
    name: mop-chart-oci
    namespace: flux-system
  
  releaseName: shipping
