apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: rsip-cart
  namespace: default
  labels:
    app.kubernetes.io/part-of: backend-services
    platform.duynhlab.dev/domain: checkout
spec:
  type: Static
  defaultValues:
    name: cart
    image_tag: "1.2.0" # {"$imagepolicy": "flux-system:cart:tag"}
    namespace: cart
    platform_backup_label: "cnpg"
    replicaCount: 2
    db_host: "pgdog-product.product.svc.cluster.local"
    db_port: "6432"
    db_migration_host: "product-db-rw.product.svc.cluster.local"
    db_secret: "product-db-cart-secret"
    db_sslmode: "disable"
    pool_max: "30"
