apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: rsip-notification
  namespace: default
  labels:
    app.kubernetes.io/part-of: backend-services
    platform.duynhlab.dev/domain: comms
spec:
  type: Static
  defaultValues:
    name: notification
    image_tag: "1.4.0" # {"$imagepolicy": "flux-system:notification:tag"}
    namespace: notification
    grpc_server: true
    replicaCount: 1
    db_host: "pgdog-platform.platform.svc.cluster.local"
    db_port: "6432"
    db_migration_host: "platform-db-rw.platform.svc.cluster.local"
    db_secret: "platform-db-notification-secret"
    db_sslmode: "disable"
    pool_max: "30"
