apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: rsip-product
  namespace: default
  labels:
    app.kubernetes.io/part-of: backend-services
    platform.duynhlab.dev/domain: catalog
spec:
  type: Static
  defaultValues:
    name: product
    namespace: product
    replicaCount: 2
    db_host: "pgdog-cnpg.product.svc.cluster.local"
    db_port: "6432"
    db_migration_host: "cnpg-db-rw.product.svc.cluster.local"
    db_secret: "cnpg-db-secret"
    db_sslmode: "disable"
    pool_max: "50"
    cache_enabled: "true"
    review_url: "http://review.review.svc.cluster.local:8080"
