apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: rsip-review
  namespace: default
  labels:
    app.kubernetes.io/part-of: backend-services
    platform.duynhne.dev/domain: catalog
spec:
  type: Static
  defaultValues:
    name: review
    namespace: review
    replicaCount: 1
    db_host: "supporting-shared-db-pooler.user.svc.cluster.local"
    db_migration_host: "supporting-shared-db.user.svc.cluster.local"
    db_secret: "review.review.supporting-shared-db.credentials.postgresql.acid.zalan.do"
    pool_max: "10"
    db_user: "review.review"
