apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: rsip-user
  namespace: default
  labels:
    app.kubernetes.io/part-of: backend-services
    platform.duynhlab.dev/domain: identity
spec:
  type: Static
  defaultValues:
    name: user
    namespace: user
    replicaCount: 1
    db_host: "supporting-shared-db-pooler.user.svc.cluster.local"
    db_migration_host: "supporting-shared-db.user.svc.cluster.local"
    db_secret: "user.supporting-shared-db.credentials.postgresql.acid.zalan.do"
    pool_max: "10"
