---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tempo/
  - pyroscope/
  - loki/
  - jaeger/
  - vector/
  - otel-collector/

labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: apm-stack
