apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: review
  labels:
    app: review-service
    component: api
spec:
  selector:
    app: review-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
