# Values for notification
name: notification
namespace: notification

replicaCount: 2

image:
  repository: ghcr.io/duynhne
  name: notification
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  portName: http

containerPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

tracing:
  enabled: true
  endpoint: "tempo.monitoring.svc.cluster.local:4318"
  sampleRate: "0.1"

