---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: user
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: product
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: cart
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: order
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: review
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: notification
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: shipping
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: k6
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: apm
  labels:
    app.kubernetes.io/managed-by: flux
    environment: local
