---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Sloth Operator (HelmRelease)
  - sloth/
  
  # PrometheusServiceLevel CRDs (9 microservices)
  - crds/

labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: slo-system
