apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# transaction-db cluster (CloudNativePG)
# Order: secrets → instance → extensions → poolers → monitoring
resources:
  - secrets/transaction-db-secret-cart.yaml
  - secrets/transaction-db-secret-order.yaml
  - instance.yaml
  # - extensions-cart.yaml
  # - extensions-order.yaml
  - poolers/
  - monitoring/podmonitor-cloudnativepg-transaction-db.yaml
  - monitoring/servicemonitor-pgcat-transaction.yaml
