apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  chart:
    spec:
      chart: postgres-operator-ui
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui
        namespace: flux-system
      version: 1.15.1
  interval: 10m
  releaseName: postgres-operator-ui
  targetNamespace: postgres-operator
  timeout: 10m
  values:
    image:
      registry: ghcr.io
      repository: zalando/postgres-operator-ui
      tag: v1.15.1
      pullPolicy: "IfNotPresent"
    envs:
      appUrl: "http://localhost:8081"
      operatorApiUrl: "http://postgres-operator:8080"
      operatorClusterNameLabel: "cluster-name"
      resourcesVisible: "False"
      targetNamespace: "*"
      teams:
        - "acid"
        - "platform"
    service:
      type: "ClusterIP"
      port: "80"
