apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/secrets.yaml
  - configmaps/vector-configs/pg-zalando-vector-config-auth.yaml
  - configmaps/vector-configs/pg-zalando-vector-config-review.yaml
  - configmaps/vector-configs/pg-zalando-vector-config-supporting.yaml
  - configmaps/monitoring-queries/postgres-monitoring-queries-auth.yaml
  - configmaps/monitoring-queries/postgres-monitoring-queries-review.yaml
  - configmaps/monitoring-queries/postgres-monitoring-queries-supporting.yaml
  - poolers/product/
  - poolers/transaction/
  - poolers/supporting/
  - instances/auth-db.yaml
  - instances/review-db.yaml
  - instances/supporting-db.yaml
  - instances/transaction-db.yaml
  - instances/product-db.yaml
