apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-zalando-vector-config
  namespace: user
data:
  vector.yaml: |
    sources:
      postgres_logs:
        type: file
        include:
          - /home/postgres/pgdata/pgroot/pg_log/*.log
        read_from: beginning
        multiline:
          start_pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC'
          condition_pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC'
          mode: continue_through
          timeout_ms: 3000

    transforms:
      add_labels:
        type: remap
        inputs: ["postgres_logs"]
        source: |
          .job = "postgres"
          .namespace = "user"
          .container = "postgres"
          .cluster = "supporting-shared-db"
          .pod = get_env_var!("POD_NAME")

    sinks:
      victorialogs:
        type: http
        inputs: ["add_labels"]
        uri: http://vlsingle-victoria-logs.monitoring.svc:9428/insert/jsonline
        encoding:
          codec: json
        framing:
          method: newline_delimited
        request:
          headers:
            VL-Time-Field: timestamp
            VL-Msg-Field: message
            VL-Stream-Fields: namespace,cluster,pod,container
            AccountID: "0"
            ProjectID: "0"
        healthcheck:
          enabled: false
