apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# product-db cluster (CloudNativePG)
# Order: secrets → instance → extensions → poolers → monitoring
resources:
  - secrets/product-db-secret.yaml
  - instance.yaml
  # - extensions.yaml
  - poolers/
  - monitoring/podmonitor-cloudnativepg-product-db.yaml
