apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
        uid: prometheus
        jsonData:
          timeInterval: 15s
          httpMethod: POST
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        uid: tempo
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: prometheus
            tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
            queries:
              - name: 'Sample query'
                query: 'sum(rate(tempo_spanmetrics_latency_bucket{$$__tags}[5m]))'
          nodeGraph:
            enabled: true
          search:
            hide: false
          serviceMap:
            datasourceUid: prometheus
          lokiSearch:
            datasourceUid: loki
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        access: proxy
        url: http://pyroscope:4040
        editable: true
        uid: pyroscope
        jsonData:
          minStep: 1s
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        uid: loki
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: '$${__value.raw}'

