{
 "title": "Go REST API Monitoring - Demo",
 "tags": [
  "golang",
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(request_duration_seconds_count, app)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "rate", "label": "Rate Interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "99th Percentile Response Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app=~\"$app\", code=~\"2..\"}[$rate])) by (le))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{app=~\"$app\", code=~\"2..\"}[$rate])) by (le))"
    }
   ]
  },
  {
   "title": "50th Percentile Response Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{app=~\"$app\", code=~\"2..\"}[$rate])) by (le))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app=~\"$app\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{app=\"$app\"}[$__range])) by (app)"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(request_duration_seconds_bucket{app=~\"$app\", le=\"0.5\"}[$rate])) + sum(rate(request_duration_seconds_bucket{app=~\"$app\", le=\"2\"}[$rate])) / 2) / sum(rate(request_duration_seconds_count{app=~\"$app\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Up Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Restarts (1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 23, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$app-[0-9a-z]{9,10}-[0-9a-z]{5}\"}[1d]))"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{app=~\"$app\"}[$__interval])) by (code)",
     "legendFormat": "REST.{{code}}"
    }
   ]
  },
  {
   "title": "Total Requests by Endpoint",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{app=~\"$app\"}[$__interval])) by (path, code)",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "RPS per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app=~\"$app\"}[$__interval])) by (kubernetes_pod_name)",
     "legendFormat": "REST.{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPS Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{app=~\"$app\"}[$rate])) by (path, code)",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Response time 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{app=~\"$app\"}[$rate])) by (le, path, code))",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Response time 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_duration_seconds_bucket{app=~\"$app\"}[$rate])) by (le, path, code))",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Response time 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{app=~\"$app\"}[$rate])) by (le, path, code))",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Memory usage per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", container_name!=\"\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", container_name!=\"\", namespace=~\"$namespace\"}[5m])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "RX {{pod_name}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "TX {{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU throttling per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", container_name!=\"\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Go GC Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_sum{app=~\"$app\"}[5m])/300",
     "legendFormat": "GC Duration"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{app=~\"$app\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{app=~\"$app\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Pagefault per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_memory_failures_total{pod_name=~\"$app-[0-9a-z]{7,8}-[0-9a-z]{5}|$app-[0-9a-z]{9,10}-[0-9a-z]{5}|$app-[0-9a-z]{5,11}|$app-[0-9a-z]{12,13}\", container_name!=\"\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod_name}} - {{failure_type}}"
    }
   ]
  }
 ]
}