---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator-oci
  namespace: flux-system
  labels:
    app.kubernetes.io/component: helm-chart
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    semver: ">=5.0.0"
