---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: infrastructure-oci
  namespace: flux-system
  labels:
    app.kubernetes.io/component: infrastructure
spec:
  interval: 5m
  url: oci://mop-registry:5000/flux-infra-sync
  ref:
    tag: local
  insecure: true
