#!/bin/bash

# SLO Deployment Script
# Deploys all SLO components: rules and alerts
# Uses Sloth to generate Prometheus rules automatically
# Note: Dashboards should be imported manually via Grafana UI

set -e

NAMESPACE="monitoring"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFINITIONS_DIR="$PROJECT_ROOT/slo/definitions"
GENERATED_DIR="$PROJECT_ROOT/slo/generated"
RULES_FILE="$GENERATED_DIR/prometheus-rules.yaml"

echo "🚀 Starting SLO deployment with Sloth..."

# Function to print output
print_status() {
    echo "[INFO] $1"
}

print_warning() {
    echo "[WARN] $1"
}

print_error() {
    echo "[ERROR] $1"
}

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    print_error "kubectl is not installed or not in PATH"
    exit 1
fi

# Check if cluster is accessible
if ! kubectl cluster-info &> /dev/null; then
    print_error "Cannot connect to Kubernetes cluster"
    exit 1
fi

print_status "Connected to cluster: $(kubectl config current-context)"

# 1. Validate SLO definitions
print_status "Validating SLO definitions..."
if [ -f "$SCRIPT_DIR/08a-validate-slo.sh" ]; then
    if ! "$SCRIPT_DIR/08a-validate-slo.sh"; then
        print_error "SLO validation failed!"
        exit 1
    fi
else
    print_warning "08a-validate-slo.sh not found, skipping validation"
fi

# 2. Generate Prometheus rules using Sloth
print_status "Generating Prometheus rules using Sloth..."
if [ -f "$SCRIPT_DIR/08b-generate-slo-rules.sh" ]; then
    if ! "$SCRIPT_DIR/08b-generate-slo-rules.sh"; then
        print_error "Failed to generate rules!"
        exit 1
    fi
else
    print_warning "08b-generate-slo-rules.sh not found, skipping rule generation"
    print_warning "Please run: ./scripts/08b-generate-slo-rules.sh manually"
fi

# Check if rules file exists
if [ ! -f "$RULES_FILE" ]; then
    print_error "Generated rules file not found: $RULES_FILE"
    print_error "Please run: ./scripts/08b-generate-slo-rules.sh first"
    exit 1
fi

print_status "✅ Prometheus rules generated"

# 3. Deploy generated SLO rules to Prometheus ConfigMap
print_status "Deploying SLO recording rules to Prometheus..."
# Check if file exists and has content
if [ ! -s "$RULES_FILE" ]; then
    print_error "Generated rules file is empty or doesn't exist: $RULES_FILE"
    print_error "Please run: ./scripts/08b-generate-slo-rules.sh first"
    exit 1
fi

# Deploy individual service ConfigMaps (generated by generate-rules.sh)
print_status "Deploying SLO rules as individual ConfigMaps per service..."
SERVICES=("auth" "user" "product" "cart" "order" "review" "notification" "shipping" "shipping-v2")

DEPLOYED_COUNT=0
for service in "${SERVICES[@]}"; do
    SERVICE_RULES_FILE="$GENERATED_DIR/${service}-rules.yaml"
    
    if [ -f "$SERVICE_RULES_FILE" ] && [ -s "$SERVICE_RULES_FILE" ]; then
        CONFIGMAP_NAME="prometheus-slo-rules-${service}"
        RULES_KEY="${service}-rules.yaml"  # Use service-specific key name for file mapping
        print_status "  Deploying rules for $service..."
        
        # Create ConfigMap with label for dynamic discovery
        kubectl create configmap "$CONFIGMAP_NAME" \
            --from-file="$RULES_KEY=$SERVICE_RULES_FILE" \
            -n "$NAMESPACE" \
            --dry-run=client -o yaml | kubectl apply -n "$NAMESPACE" -f - > /dev/null 2>&1
        
        # Add labels for dynamic discovery
        kubectl label configmap "$CONFIGMAP_NAME" -n "$NAMESPACE" \
            app=prometheus slo-rules="true" --overwrite > /dev/null 2>&1
        
        if [ $? -eq 0 ]; then
            print_status "    ✅ Created ConfigMap: $CONFIGMAP_NAME"
            DEPLOYED_COUNT=$((DEPLOYED_COUNT + 1))
        else
            print_error "    ❌ Failed to create ConfigMap: $CONFIGMAP_NAME"
        fi
    else
        print_warning "  ⚠️  Rules file not found: $SERVICE_RULES_FILE"
    fi
done

if [ "$DEPLOYED_COUNT" -gt 0 ]; then
    print_status "✅ Deployed $DEPLOYED_COUNT SLO ConfigMaps (one per service)"
else
    print_error "❌ No ConfigMaps were deployed!"
    exit 1
fi


# 4. Update Prometheus configuration
print_status "Updating Prometheus configuration..."
kubectl apply -f "$PROJECT_ROOT/k8s/prometheus/configmap.yaml" || print_warning "Prometheus ConfigMap update skipped (may need manual update)"

# CRITICAL: Restart Prometheus to pick up the new ConfigMaps in projected volume
# Projected volumes don't automatically update when ConfigMaps are created
print_status "Restarting Prometheus to mount new SLO rules ConfigMaps..."
kubectl rollout restart deployment/prometheus -n "$NAMESPACE" || print_warning "Prometheus restart skipped"
print_status "✅ Prometheus configuration updated"

# 5. Wait for Prometheus to restart
print_status "Waiting for Prometheus to restart..."
if kubectl get deployment prometheus -n "$NAMESPACE" &> /dev/null; then
    kubectl rollout status deployment/prometheus -n "$NAMESPACE" --timeout=300s || print_warning "Prometheus rollout check failed"
    print_status "✅ Prometheus restarted successfully"
else
    print_warning "Prometheus deployment not found, skipping restart check"
fi

# 6. Verify deployment
print_status "Verifying SLO deployment..."
FOUND_CONFIGMAPS=0
for service in "${SERVICES[@]}"; do
    CONFIGMAP_NAME="prometheus-slo-rules-${service}"
    if kubectl get configmap "$CONFIGMAP_NAME" -n "$NAMESPACE" &> /dev/null; then
        FOUND_CONFIGMAPS=$((FOUND_CONFIGMAPS + 1))
    fi
done

if [ "$FOUND_CONFIGMAPS" -eq "${#SERVICES[@]}" ]; then
    print_status "✅ All SLO ConfigMaps deployed ($FOUND_CONFIGMAPS/${#SERVICES[@]})"
elif [ "$FOUND_CONFIGMAPS" -gt 0 ]; then
    print_warning "⚠️  Only $FOUND_CONFIGMAPS/${#SERVICES[@]} SLO ConfigMaps found"
else
    print_warning "⚠️  SLO ConfigMaps not found"
fi

# Verify rules files are mounted in Prometheus pod
print_status "Verifying rules files in Prometheus pod..."
PROMETHEUS_POD=$(kubectl get pods -n "$NAMESPACE" -l app=prometheus -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
if [ -n "$PROMETHEUS_POD" ]; then
    RULES_COUNT=$(kubectl exec -n "$NAMESPACE" "$PROMETHEUS_POD" -- ls -1 /etc/prometheus/slo-rules/*.yaml 2>/dev/null | wc -l || echo "0")
    if [ "$RULES_COUNT" -gt 0 ]; then
        print_status "✅ Found $RULES_COUNT SLO rule file(s) in Prometheus pod"
    else
        print_warning "⚠️  No rule files found in Prometheus pod (may need to wait for restart)"
    fi
else
    print_warning "⚠️  Prometheus pod not found, skipping verification"
fi

# 7. Display access information
print_status "🎉 SLO deployment completed successfully!"
echo ""
echo "📊 Access your services:"
echo "   Grafana:     kubectl port-forward -n $NAMESPACE svc/grafana-service 3000:3000"
echo "   Prometheus:  kubectl port-forward -n $NAMESPACE svc/prometheus 9090:9090"
echo ""
echo "📈 Import Sloth Dashboards (Manual):"
echo "   1. Open Grafana UI: http://localhost:3000"
echo "   2. Go to Dashboards → Import"
echo "   3. Import by ID:"
echo "      - Detailed SLOs: ID 14348"
echo "      - Overview:      ID 14643"
echo "   4. Select datasource: Prometheus (UID: prometheus)"
echo ""
echo "   Note: These dashboards visualize SLO metrics generated by Sloth."
echo "   - Detailed SLOs (ID: 14348): Shows detailed SLO metrics per service"
echo "   - Overview (ID: 14643): Shows high-level SLO overview across all services"
echo ""
echo "📈 SLO Metrics to check in Prometheus (per service):"
echo "   - slo:sli_error:ratio_rate5m{service=\"<service-name>\"}"
echo "   - slo:sli_error:ratio_rate30m{service=\"<service-name>\"}"
echo "   - slo:error_budget_burn_rate:ratio{service=\"<service-name>\"}"
echo "   - slo:error_budget_remaining:ratio{service=\"<service-name>\"}"
echo ""
echo "🔍 Troubleshooting:"
echo "   - Check Prometheus rules: http://localhost:9090/api/v1/rules | grep slo:"
echo "   - Check SLO metrics: http://localhost:9090/api/v1/query?query=slo:sli_error:ratio_rate5m"
echo "   - Verify source metrics: http://localhost:9090/api/v1/query?query=request_duration_seconds_count"
echo ""
echo "🚨 SLO Alerts to monitor (per service):"
echo "   - <Service>HighErrorRate (Page Alert)"
echo "   - <Service>HighErrorRate (Ticket Alert)"
echo "   - <Service>HighLatency (Page Alert)"
echo "   - <Service>HighOverallErrorRate (Page Alert)"
echo ""
echo "📋 Services with SLOs:"
for service_file in "$DEFINITIONS_DIR"/*.yaml; do
    if [ -f "$service_file" ] && [ "$(basename "$service_file")" != "all-services.yaml" ]; then
        service_name=$(grep "^service:" "$service_file" | head -1 | awk '{print $2}' | tr -d '"')
        echo "   - $service_name"
    fi
done
echo ""
print_status "SLO deployment completed! 🎯"
