apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pss-baseline.yaml
  # - pss-restricted-apps.yaml # DISABLED 2026-08-17 — see that file's header
  - disallow-latest-tag.yaml
  - require-resources.yaml
  - require-probes.yaml
  - disallow-default-namespace.yaml
  - default-deny-networkpolicy.yaml
  - cleanup-controller-rbac.yaml
  - cleanup-completed-pods.yaml
