---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - product-db-secret.yaml
  - transaction-db-secret-cart.yaml
  - transaction-db-secret-order.yaml

labels:
  - pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: database-stack
      app.kubernetes.io/managed-by: flux
