apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-go-api
  namespace: monitoring-demo
  labels:
    app: demo-go-api
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: demo-go-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

