apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes/
  - microservices/
  - postgres/
  - kong/
  - victoriametrics/
  - observability/
  - valkey/
  - gitops/
  - watchdog.yaml
