---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal-operator
  namespace: flux-system
  labels:
    app.kubernetes.io/component: helm-repository
spec:
  interval: 1h
  url: https://alexandrevilain.github.io/temporal-operator
